### ISSUE TITLE
How to displayed the stats info per 5 seconds ? 

### ISSUE THREAD

**Issue by lioncui** [docker/docker-py#1009]
How to set stats api display interval ?
I want to display it per 5 seconds not every seconds.
I not found any support about this issues.

**Comment by TomasTomecek** [comment]
This seems to be hardcoded as the server API call doesn't take any parameters:

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.22/#get-container-stats-based-on-resource-usage
https://github.com/docker/docker/blob/168b490062aed36bf95426d9d66dcf5703842016/daemon/stats_collector_unix.go#L60

Since it's one second, it doesn't mean you have to obey, you can write the logic locally, something like:

```python
while True:
  time.sleep(5.0)
  stats = d.stats(container, stream=False)
```

if that won't work, this definitely should:

```python
while True:
  time.sleep(5.0)
  stats = next(d.stats(container, stream=True))
```
