### ISSUE TITLE
create_container not support --cgroup-parent param

### ISSUE THREAD

**Issue by HusterWan** [docker/docker-py#1067]
i want to set --cgroup-parent when create container ,but found docker-py not support this param

**Comment by shin-** [comment]
It is supported.

```python
import docker
c = docker.Client(...)
host_cfg = c.create_host_config(cgroup_parent='test', ...)
c.create_container(image, cmd, host_config=host_cfg, ...)
```

**Comment by HusterWan** [comment]
sorry, my bad! but in the docker-py document,  it does not mention the cgroup_parent param in host-config definition.

**Comment by waynr** [comment]
@shin- I agree that this should be documented, I'd be happy to submit a PR if you point me in the right direction.

**Comment by waynr** [comment]
@shin- is there any particular reason that the `cgroup_parent` option isn't available for the "high-level API" `Container` object (https://docker-py.readthedocs.io/en/stable/api.html#module-docker.api.container)? I am now finding that in order to specify a `--cgroup-parent` on the underlying container I have to rewrite code I had already written with `Container` in the style of what you show in your code snippet above.

Aside from the obvious fact that it's annoying and counterintuitive to have to rewrite my code to take advantage of features not available on the recommended high level API, the main reason I find this objectionable is that the `ApiClient.create_containers` and `docker.containers.run` have misleadingly similar lists of parameters that take different values--in the former you are required to define a list of volumes in `create_containers` as well as a more complex data structure in a separate call to `create_host_config`:

```python
        host_config = None
        binds = {
            m2_repo_dir: m2_repo_dir,
            runhistorian_dir: runhistorian_container_dir
        }

        if os.path.isfile('/.dockerenv'):
            host_config = self.api_client.create_host_config(
                cgroup_parent=self.__get_current_cgroup(),
                binds=binds,
            )
        else:
            host_config = self.api_client.create_host_config(
                binds=binds,
            )

        container_id = self.api_client.create_container(
            'jrh:latest', mvn_cmd,
            host_config=host_config,
            detach=True,
            environment={
                'JAVA_HOME': java_home,
            },
            volumes=binds.keys(),
        )

```

vs

```python
        cgroup_parent = None
        if os.path.isfile('/.dockerenv'):
            cgroup_parent = self.__get_current_cgroup(),

        self.__jenkins_container = self.client.containers.run(
            'jrh:latest', mvn_cmd,
            detach=True,
            cgroup_parent=cgroup_parent,
            environment={
                'JAVA_HOME': java_home,
            },
            volumes={
                m2_repo_dir: m2_repo_dir,
                runhistorian_dir: runhistorian_container_dir,
            }
        )
```

If you're open to accepting a PR to add the `cgroup_parent` option to `DockerClient.containers.run` and willing to provide some guidance I'd be glad to contribute.

**Comment by waynr** [comment]
Nevermind my previous comment, after browsing through the source working on a different problem I see that there is an undocumented `cgroup_parent` parameter available for `docker.models.containers.create_container`.
