### ISSUE TITLE
Proposal: A new user-focused API

### ISSUE THREAD

**Issue by bfirsh** [docker/docker-py#1086]
### Problem

The current API is a great wrapper around the REST API, but many common tasks that users want to do don't necessarily map directly to REST API calls. For example, simply running a container is [a rather convoluted process](https://gist.github.com/bfirsh/d3435b3f26033dd533cc4732639ae2ef#file-getting-started-python-md).
### Proposal

I am proposing we add a higher-level API focused on what users want to do. It should be the default, recommended way of using docker-py.

It could look something like this:

``` python
>>> import docker
>>> client = docker.from_env()

>>> client.containers.run("ubuntu", "echo hello world")
'hello world\n'

>>> client.containers.run("ubuntu", "tasks/reticulate-splines", detach=True)
<Container '45e6d2de7c54'>

>>> client.containers.list()
[<Container '45e6d2de7c54'>, <Container 'db18e4f20eaa'>, ...]

>>> container = client.containers.get('45e6d2de7c54')

>>> for line in container.logs(stream=True):
...   print line
Reticulating spline 2...
Reticulating spline 3...
```

[See this sketch of a README for a more examples of how it could work.](https://github.com/bfirsh/docker-py/blob/user-api/README.md) It intentionally starts with a common thing that users want to do which is complex with the current API: running containers.
### Backwards compatibility

This is a good excuse for 2.0. ;)

The new API can be built on top of the current lower-level API. The current API can be made available to users in case they want that extra flexibility and to give them a seamless migration path (`client.api.create_container(...)` or something like that).
### See also
- This is building on top of @shin-'s work in #788.
- Related issues: #1049 #417 
- [dockerrun](https://github.com/bfirsh/dockerrun), an example of how a `run()` method could work.

**Comment by TomasTomecek** [comment]
I agree that having the OO abstraction in docker-py would be great since that's what likely everyone is doing in their python projects using docker-py. (e.g. this is what I have in sen: [common base class](https://github.com/TomasTomecek/sen/blob/9fce2539be23306f1fabfd7bed2e210737c08df6/sen/docker_backend.py#L139) and object specific classes for [container](https://github.com/TomasTomecek/sen/blob/9fce2539be23306f1fabfd7bed2e210737c08df6/sen/docker_backend.py#L434) and [image](https://github.com/TomasTomecek/sen/blob/9fce2539be23306f1fabfd7bed2e210737c08df6/sen/docker_backend.py#L248) -- hence I would love to contribute some of the code back to this new API)

But please, make it backwards compatible. There's so many tools built on top of docker-py already. So I don't see why you would have to ~~remove~~ deprecate the already-used, stable and efficient low-level API.

**Comment by bfirsh** [comment]
A prototype here, if anyone's interested: https://github.com/bfirsh/docker-sdk-python

**Comment by bfirsh** [comment]
Implemented in https://github.com/docker/docker-py/issues/1186!
