### ISSUE TITLE
kernel_memory and mem_reservation support

### ISSUE THREAD

**Issue by yank1** [docker/docker-py#1128]
HI 

the kernel_memory and mem_reservation is very important,
can we support it on create container ?

**Comment by mattarchie** [comment]
I see you've submitted a pull request which seems to be just about ready for merging. I'm glad to see that this will be supported soon.

In the meantime (or if someone needs to use an older version), I got around this issue by using update_container, which does support both of those. My code uses the same function for creating and updating a container, so if my create flag is set, then I create the container before updating it, otherwise, I update the existing container. Depending on your code, this approach could actually offer an improvement by allowing the same code to be reused for both create and update cases.
