### ISSUE TITLE
pip install docker-py causes ImportErrors errors with subsequent pip calls

### ISSUE THREAD

**Issue by tallandtree** [docker/docker-py#1169]
When I install the latest docker-py module via pip (versions 1.8.0, 1.8.1, 1.9.0), a newer version of requests module (2.11.1) is also installed, although an existing OS version exists. After this, pip is broken. 
OS: debian jessie
Command:
```
# pip install docker-py
Downloading/unpacking docker-py
  Downloading docker_py-1.9.0-py2.py3-none-any.whl (42kB): 42kB downloaded
Requirement already satisfied (use --upgrade to upgrade): ipaddress>=1.0.16 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Downloading/unpacking requests>=2.5.2 (from docker-py)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB): 514kB downloaded
Requirement already satisfied (use --upgrade to upgrade): websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname>=3.5 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/lib/python2.7/dist-packages (from docker-py)
Installing collected packages: docker-py, requests
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed docker-py requests
Cleaning up...

# pip uninstall docker-py
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```
I've to remove /usr/local/lib/python2.7/dist-packages/requests to solve the issue with pip.
When installing docker-py via pip, pip should not upgrade requests.

**Comment by TomasTomecek** [comment]
This is not an issue of docker-py, instead it's an issue of either python package management or distribution package management. tl;dr is that you shouldn't mix those two ecosystems.

If a python package requires package X in version Y, and X-Y breaks other packages, that's not a fault of the former python package. It doesn't know what versions are available on the system, nor does it know what packages in which versions other packages require. That's the responsibility of package manager.

docker-py maintainers identified [range](https://github.com/docker/docker-py/blob/master/setup.py#L12) of versions in which their package is working. Your version is not in that range.

Since the version of requests you have is pretty outdated. I would suggest installing docker-py in a new clean virtualenv or in a docker container (since newest requests break your host system).

**Comment by tallandtree** [comment]
I agree partly, but there is no reason for docker-py to upgrade `requests` to the latest version. As far as I can see (and test), it works with the installed (debian jessie default package) version of requests in /usr/lib/python2.7/dist-packages.
Main issue is indeed with incompatibility of requests 2.11.1 and installed (default debian jessie) pip version. But then it would make sense to also upgrade pip.
