### ISSUE TITLE
Client IP with Swarm spans over the nodes

### ISSUE THREAD

**Issue by diegito** [docker/docker-py#1278]
When connecting to a specific node inside the swarm to retrieve data of the specific docker daemon, the connection spans over the nodes of the swarm and randomly accesses one of them. 
I know this is the expected behaviour of the swarm, but on the Docker remote API I get to access exactly that node.

What I did:
- setup 5 nodes (3m/2w) with docker machine. The nodes were on
  192.168.99.100~104
- installed sherpa to access the docker daemon with the following:

```
docker service create --name sherpa --mount type=bind,source=/var/run/docker.sock,target=/tmp/docker.sock --mode global -p 4550:4550 djenriquez/sherpa --allow
```

and accessed the Remote API `http://192.168.99.101:4550/containers/json` from the browser. This works as expected, retrieving that node's containers also when repeatedly queried.

When connecting via **docker-py** using the following code, it retrieves one of the random node's data.

```
from docker import Client
c = Client("192.168.99.101:4550")
print c.containers()
```

**Comment by zebpalmer** [comment]
_In docker years, this (untouched) case is ancient... but it is the highest google result for docker swarm sherpa (as I found searching for unrelated issue). So I'll drop a comment here for anyone having a similar problem. I suggest this case be closed_ 

I'm more surprised you weren't getting random results with direct http, than the fact you were with docker-py. Given the service command shown, I would expect the behavior you experienced with docker-py as that request is handled through the swarm routing mesh.

To mitigate this behavior, you need to expose sherpa on the host rather than via the routing mesh.  Swap out the ` -p 4550:4550 ` with `--publish mode=host,target=4550,published=4550` and it works like a charm. 

More info: https://docs.docker.com/engine/swarm/services/#publish-ports
