### ISSUE TITLE
refresh container.attrs

### ISSUE THREAD

**Issue by dimaqq** [docker/docker-py#1375]
Following code runs into a problem:

```
container = docker.from_env().containers.create(image=...)
container.start()
ip = container.attrs["NetworkSettings"]["Networks"]["bridge"]["IPAddress"]
# ip == "" :(, but I get it.
time.sleep(...)
ip = container.attrs["NetworkSettings"]["Networks"]["bridge"]["IPAddress"]
# ip == "" :(, still ???:-(???
```

**Comment by ah19** [comment]
I have run into a similar problem with myself -- try running `container.reload()`

**Comment by lgilz** [comment]
I think this is a serious Issue as Container.create returns a container-object. And I'm especially interested in its ExitCode (attrs['State]['ExitCode'], But this always remains 0, even if the container is exited with a non-zero ExitCode. 
Even its status remains unchanged ('created') instead of ('exited').

I think, that the container-object you get back from containers.create() is actually nothing else than the response of the docker-api and does not follow the changing state of it's container. With the package, its like calling an api and you have to call client().containers.get(container.id) again, if you want to have updated information

However, this should definitely be mentioned in the Documentation more clearly - as the description of a container-object is completely misleading!

**Comment by felicitychou** [comment]
I meet this problem too. With the help of @ah19 , I solve it.  

At the same time, I agree with @lgilz.

**Comment by cdaringe** [comment]
man, this was painful.  thanks all.

**Comment by cdaringe** [comment]
actually, `reload` doesn't get the 'HostConfig' up-to-date.  i still do not see my exposed ports
