### ISSUE TITLE
The exclusion patterns of .dockerignore are not respected

### ISSUE THREAD

**Issue by lelit** [docker/docker-py#1514]
This is a follow-up to what I explained in issue #1117: the way #1455 implemented the function `utils.build.exclude_paths()`, in particular by slicing the patterns into an _include_ and an _exclude_ lists, is wrong, as the [script attached to that issue](https://github.com/docker/docker-py/issues/1117#issuecomment-286694944) shows.

I think that the only way to get the right behaviour is to consider the patterns as an ordered list of rules that must be applied sequentially on each item obtained by iterating the filesystem subtree, something like the function `valid_paths()` I proposed [here](https://github.com/docker/docker-py/issues/1117#issuecomment-268176859), that I'm (still) using as a fixup.

**Comment by sergei-ivanov** [comment]
Sorry if I am hijacking the topic here, but I think the problem we are seeing is related to this issue.
We have a `.dockerignore` file for a Maven project, where we are ignoring everything except for the files that we are copying into the image. We use explicit file paths in exclusions now, something like this:

```
*
!docker/Dockerfile
!docker/run.sh
!app1/target/*.jar
!app1/src/main/resources/*.properties
!app2/stub/target/*.jar
!app2/stub/src/main/resources/*.properties
```

And we tried to replace them with `**`, but that did not work at all, because the files are not added to the build context:

```
*
!docker/Dockerfile
!docker/run.sh
!**/target/*.jar
!**/src/main/resources/*.properties
```

Result:

```
Step 6/19 : COPY app1/target/app1-0.0.1-SNAPSHOT-spring-boot.jar /usr/local/app1/app1-spring-boot.jar
lstat app1/target/app1-0.0.1-SNAPSHOT-spring-boot.jar: no such file or directory
```

**Comment by shin-** [comment]
Newer versions should handle everything properly now.
