### ISSUE TITLE
Updating a Service in reality recreates it.

### ISSUE THREAD

**Issue by Nils-K** [docker/docker-py#1521]
When trying to update a Service using the update() call, all existing attributes of the Service are reset.

For instance, given a Service that has Env, Mounts defined, performing a Service.update(image=new_image) will result in a service with the updated image definition, but without the previously existing Env and Mounts definitions.

This means that update() currently behaves as if you were to perform a Service.delete(), Service.create(). I would expect Service.update() to "copy" the existing Service definition and apply my changes.

In my specific case this is important because my service has replicas, deleting the service and recreating it (the current observed behavior) completely defeats the benefits of having a replica in the first place, as deleting the Service will destroy all running replicas at once.

**Comment by ornoone** [comment]
it seem this behavior is intended from the docker api (https://github.com/docker/swarmkit/issues/1394).
you must provide to your update all the parameters to preserve the old definition.

**Comment by Sarklin** [comment]
OK, the reasoning behind that makes sense.

However, the Python API doesn't provide a clean/easy way to set all required attributes making it very complicated to update a service (I currently have to divert to the Low-Level API).

Are there plans to expand the Python API to either implement update() as per my initial suggestion, that is copying the entire existing service definition and apply the differences?
Or, alternative expand the Service Object so that we can completely reconstruct the object ourselves? Currently one is only able to set all required parameters/attributes through the LLA.

**Comment by ornoone** [comment]
I have wrote a PR to add a Service.update_preserve for this (https://github.com/docker/docker-py/pull/1561)

**Comment by shin-** [comment]
The parameter for `fetch_current_spec` can be used for this in recent versions.
