### ISSUE TITLE
Documentation as pdf

### ISSUE THREAD

**Issue by fkromer** [docker/docker-py#1963]
Could you provide the [readthedocs documentation](https://docker-py.readthedocs.io/en/stable/) as pdf as well?

**Comment by shin-** [comment]
Hi @fkromer ,

I looked at our options for using sphinx to produce PDF output, but it turns out that `rst2pdf` is abandoned and straight up breaks with recent versions of Python, and the `latex` output produces a file that is too complex to be properly converted to a PDF file.

If this were an easy fix I'd be happy to add it to our release process, but given the situation I'm afraid there isn't much I can do to help.

**Comment by fkromer** [comment]
As far as I can remember PDF generation is a builtin feature of readthedocs. For the "configuration in GitHub" refer to e.g. [`tox` (search for "sphinx")](https://github.com/tox-dev/tox/search?utf8=%E2%9C%93&q=sphinx&type=). I am not quite sure how a project had to be configured in the readthedocs dashboard exactly anymore...

**Comment by shin-** [comment]
Ok, I enabled it on RTD: https://media.readthedocs.org/pdf/docker-py/stable/docker-py.pdf

HTH!

**Comment by fkromer** [comment]
Great, thanks a lot.
