### ISSUE TITLE
client.images.build : cannot build if Dockerfile ADDs files from relative path

### ISSUE THREAD

**Issue by magowiz** [docker/docker-py#2079]
Hi,
I'm trying to build an image having a dockerfile, and some other files to put into image on same folder tree of dockerfile, for example:  ~/proj/dockerfile and ~/proj/script/file-to-add.sh

Anyway when I run : 
```
fname='/home/magowiz/proj/Dockerfile-master'
dock_file = open(fname, 'rb'
path = os.path.dirname(fname)
image = self.client.images.build(fileobj=dock_file, tag=ltag, path=path)
```

I get an error it cannot find the "file-to-add.sh" : 
`docker.errors.BuildError: ADD failed: stat /var/lib/docker/tmp/docker-builder794925518/scripts/start.sh: no such file or directory`

It is evident for me that build is searching the file into wrong place, how can I tell to build to use as directory the one in which Dockerfile resides ?

**Comment by shin-** [comment]
Do this instead:
```python
fname='/home/magowiz/proj/Dockerfile-master'
path = os.path.dirname(fname)
image = self.client.images.build(path=path, dockerfile='Dockerfile-master')
```

By default, `fileobj` sends a Dockerfile without any build context, which is why you can't `ADD` anything. `fileobj` also lets you pass an entire build context (tarball containing context + Dockerfile) if you set `custom_context` to `True`, but in your case, it's much simpler if you just set `path` and `dockerfile` and let the SDK take care of generating the context for you.
