### ISSUE TITLE
How to get containers.run(image,detach=False) to print logs into python console?

### ISSUE THREAD

**Issue by SysEngDan** [docker/docker-py#2268]
When I execute containers.run(image,detach=False) from a python:3.6 container, the container runs but no logs are printed in the console. If I separately run containers.log or docker logs, I get logs. How can I get these to be returned in the console from my .py script without separately running container.logs()?

**Comment by ijc** [comment]
Is it possible that your container is only producing output on `stderr`? Only `stdin` is included in the result of `run` by default. You can pass `stderr=True` to change this. By contrast `containers.log` (and `docker log`) include stderr by default.

```python
>>> import docker
>>> client = docker.from_env()
>>> client.containers.run('alpine', ['/bin/sh', '-c', 'echo hello world'])
'hello world\n'
>>> client.containers.run('alpine', ['/bin/sh', '-c', 'echo hello world 1>&2'])
''
>>> client.containers.run('alpine', ['/bin/sh', '-c', 'echo hello world 1>&2'], stderr=True)
'hello world\n'
```

This is documented in the docs for `run`, although it's a bit buried in the midst of the long list of `kwargs`
From https://docker-py.readthedocs.io/en/stable/containers.html:
> * stdout (bool) – Return logs from STDOUT when detach=False. Default: True.
> * stderr (bool) – Return logs from STDERR when detach=False. Default: False

I'm going to speculatively close the issue since I think that's most likely the answer, please do reopen if that doesn't help though.
