### ISSUE TITLE
How to test the `wait(condition="removed")` ?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [docker/docker-py#2270]
I am referring to [containers.Container.wait](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.wait).

How can the condition 'removed' be tested?
1. When I do stop a container first
2. Then I can wait for condition 'not-running' --> `wait(condition="not-running")`

But
1. When I remove a container first and
2. When I try to wait for condition 'removed'  --> `wait(condition="removed")`
3. Then I will get a 404 error - container not found

So how/when can  `wait(condition="removed")` be used usefully?

**Comment by inkychris** [comment]
I think this is a fundamental "feature" of the daemon itself as commented in the [moby source](https://github.com/moby/moby/blob/882e26a4a883c38a838232852529c86b90f8cf28/daemon/wait.go#L16). The *not found* error is essentially expected behaviour, it's just that expected behaviour shouldn't be *exceptional* so one would assume the `wait()` method would handle this for us or perhaps the daemon not respond with an error. That said `wait(condition="removed")` is still somewhat useful if you catch the exception yourself:

```python
def wait_for_rm(container):
    try:
        container.wait(condition='removed')
    except docker.errors.NotFound:
        return False
    return True

wait_for_rm(container)
```

This removes the need to poll the daemon yourself, ie:

```python
def container_exists(container):
    try:
        container.reload()
    except docker.errors.NotFound:
        return False
    return True

while container_exists(container):
    time.sleep(1)
```

It would be nice if the container's `wait()` method did this for us, as would be expected but this is similar behaviour to the daemon itself. One potential benefit I can think of for using the `wait()` method over manually looping `reload()` or other methods is that it may be able to better optimise the way it polls the daemon while it's blocking.

Given that *removed* and *not found* are essentially synonymous in this case, perhaps it could be argued that the daemon should simply respond with a success rather than error as the daemon not being able to find the container if it has been removed is not *exceptional*, although you could argue that the difference is that *removed* implies it existed at some point and the daemon currently can't determine that.

**Comment by Tset-Noitamotua** [comment]
Thank you a lot. Your first example is exactly what I needed. Easy and effective.

:heart:  :heart:  :heart:
