### ISSUE TITLE
Need way to interrupt read operation on stream socket

### ISSUE THREAD

**Issue by leth** [docker/docker-py#272]
The stream read operation is currently blocking without a timeout, and there's no API for interrupting the stream.

**Comment by adewes** [comment]
I also encountered this problem when trying to read from the results of the `Container.logs(stream=True)` endpoint. It would be great if there was a way to just get the `HTTPResponse` object from requests here, as this allows non-blocking reads from the result (AFAIK). Otherwise it would be great to add an `async` parameter to the function so that it can be used in non-blocking context.

My use case:

I'm trying to use the function in a non-blocking generator loop where on every iteration I want to check the status of the container, return the new log output, and yield control to the caller. With the current implementation of the `logs` endpoint this seems not possible.

**Comment by shin-** [comment]
Fixed by #1965
