### ISSUE TITLE
Getting logs from commands

### ISSUE THREAD

**Issue by feakuru** [docker/docker-py#2798]
Is it possible to get logs from commands such as `client.images.pull`? I found that the `ImageCollection` doesn't do anything with the logs it gets from Docker, and I would like to be able to access them, preferably as the command is running. Is there a way to do that? If not, would it be hard to implement this feature? Thanks in advance.

**Comment by feliperuhland** [comment]
Hi @feakuru 

Yes, you can do that with the [pull method](https://docker-py.readthedocs.io/en/stable/api.html#docker.api.image.ImageApiMixin.pull) from low-level API.

**Note** There´s an example there, but it is outdated because the correct call is `cli.api.pull`. I´m going to open a pull request to fix that.

Have a nice day :)
