### ISSUE TITLE
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory (Ubuntu 22.04)

### ISSUE THREAD

**Issue by microhobby** [docker/docker-py#2982]
Ubuntu 22.04 is using openSSL 3.0 as default and the project is tied to the `pyOpenSSL==18.0.0` that does not support it: https://www.pyopenssl.org/en/18.0.0/install.html#supported-openssl-versions

**Comment by milas** [comment]
This will be fixed in the upcoming release - the dependencies have been upgraded and transitive dependencies are no longer pinned. Additionally, `requests[security]` no longer exists upstream, as the TLS situation is much improved in recent Python versions, so `pyOpenSSL` is no longer required:
```
$ pip install git+https://github.com/docker/docker-py.git@main
...
$ pip freeze
certifi==2022.6.15
charset-normalizer==2.1.0
docker @ git+https://github.com/docker/docker-py.git@ab43018b027e48c53f3cf6d71ce988358e3c204e
idna==3.3
packaging==21.3
pyparsing==3.0.9
requests==2.28.1
urllib3==1.26.11
websocket-client==1.3.3
```
(from HEAD in an Ubuntu 22.04 container)
