### ISSUE TITLE
Docker Hub v1 API Deprecation

### ISSUE THREAD

**Issue by afonsoaugusto** [docker/docker-py#3041]
Hi,

I have a notice the [Docker has planned to deprecate the Docker Hub v1 API endpoints that access information related to Docker Hub repositories on September 5th, 2022.](https://www.docker.com/blog/docker-hub-v1-api-deprecation/)

Will the library (current version **6.0.0** or **5.0.3** version) be affected by the deprecation?

I current using the version **4.4.4** because is compatible with python 2.7.
Is possible to update this version?

Thanks

**Comment by afonsoaugusto** [comment]
In my tests with version 4.4.4.
Yesterday (29/08/2022) I receive this error:
 ```sh
Logging into https://index.docker.io/v1/ for user MyUser failed - 500 Server Error for [http://localhost:2375/v1.41/auth:](http://localhost:2375/v1.41/auth) Internal Server Error (\"Get \"[https://registry-1.docker.io/v2/\](https://registry-1.docker.io/v2//)
```
But today (30/08/2022) in maintenance time (August 30, 2022 8:00AM - 10:00AM PDT) I don't receive that error.

**Comment by milas** [comment]
The registry authentication is not part of the repo routes v1 deprecation. This library will not be affected as it communicates with the Docker Engine API rather than Docker Hub.

There was an unrelated infrastructure incident with Docker Hub around the time frame you were seeing issues.

Here's the hub status page for the future: https://status.docker.com/
