### ISSUE TITLE
Require user to specify API version or use unversioned API endpoint

### ISSUE THREAD

**Issue by discordianfish** [docker/docker-py#402]
Hi,

I think the current situation around versioning is less than ideal if you don't provide a API version.
In that case docker-py uses the latest version which is required by all features it uses.

This means that you can't use a docker-py version which supports a feature which was more recently implemented than the oldest docker host you need to connect to. From a ops POV that requires you to pin the docker-py version especially if you depend on 3rd party tools (like ansible) where it's not easy to provide the API version[1]. 

This is really hard to handle and I think there are two ways better than this:

1) Be explicit and always provide a version. This way things can't break and you can always use the most recent docker-py version. This is definitely the preferred way but requires 3rd party tools who use docker-py to provide reasonable ways to set the version.
2) Be lazy and use the unversioned API endpoint. This works for most things and if an API endpoint has changed, the daemon will error out.

From a pragmatic POV I would just use the unversioned API endpoint and leave it to the users whether they want to provide a version. If we want to force people into being explicit (and therefor make sure all tools interacting with docker via docker-py provide easy ways to specify the version), we should require a version.
Anyway, I think just using the latest version by default isn't ideal.

[1]: It's possible to specify the version, but you need to do that each time you use that docker module.

**Comment by gzur** [comment]
But how about allowing version to be set to '**auto**' - in which case the API uses the newest version the daemon supports?

**Comment by michaelbarton** [comment]
This issue is somewhat old, I'd like to add a few points because I think API
versioning is still relevant.

I was working on some code that I hadn't worked on in a while and I immediately
got an error when I ran the tests for the first time without changing anything:

~~~ python
    def get_image_tags(docker_dict):
        """
        Returns list of all Docker image names with and without tags.
        E.g. includes both python and python:2.7
        """
        return reduce(lambda acc, x: acc + [x, x.split(":")[0]],
>               docker_dict['RepoTags'], [])
E       TypeError: reduce() arg 2 must support iteration
~~~

As I'm familiar with Docker, I assumed that this might be because code I had
written was trying to use an API field that had changed between versions and I
likely had a newer version of Docker installed. Looking through the docker-py
issues lead me to this one and that I could use the following code to fix my
problem:

~~~ python
def client():
    args = docker.utils.kwargs_from_env(assert_hostname = False)
    args['version'] = "1.12"
    return docker.Client(**args)
~~~

We're working on [wrapping bioinformatics software in docker images][] and we
have a python CLI that uses the docker/docker-py library to manage this. I
think the solution we'll follow is to specify a specific version of the Docker
API in this client and then ask that users have a least this version of Docker
installed. This should prevent API errors such as the one above from occuring.

[biobox]: http://bioboxes.org/

That's all I have to add. I don't have any specific requests, however I thought
it worth adding my opinion should this conversation resurface again in future.

**Comment by bfirsh** [comment]
Using the API without a version will be deprecated in the next release: https://github.com/docker/docker/pull/27830

This makes this a issue a moot point, but I think `version='auto'` solves the problem pretty well anyway. :)
