### ISSUE TITLE
stream=False is undocumented / Getting build image IDs is undocumented

### ISSUE THREAD

**Issue by Julian** [docker/docker-py#459]
The (different) return value that one gets if passing `stream=False` is undocumented (nor is whether the default `True` or `False`), which is to return a 2-tuple of `image_id, output`. The fact that `stream=False` can get you the image ID of your new image is also undocumented (which perhaps would be useful to have available even if you pass `stream=True`, since until I read the source code for an unrelated reason, I had asked whether it was possible to get the image ID, and since it seemed like the answer was "no", resorted to passing in my own UUID4 to use as the tag and using that).

**Comment by Julian** [comment]
`stream=False` actually doesn't work at all seemingly, it gets overridden by https://github.com/docker/docker-py/blob/master/docker/client.py#L438-L439

**Comment by shin-** [comment]
That's because it's been deprecated for a long time already: see https://github.com/docker/docker-py/blob/master/docker/client.py#L438

You can use the following code snippet to get the built image ID: https://github.com/docker/docker-py/issues/392#issuecomment-62293783

We're working on having a tools module that could contain helpful code like this, hopefully soon.

**Comment by Julian** [comment]
Oh. OK -- is the deprecation documented somewhere, I don't see it at http://docker-py.readthedocs.org/en/latest/api/?

**Comment by shin-** [comment]
You're right, it's not explicitly mentioned anywhere. I'll look into it.
