### ISSUE TITLE
docker-py fails silently on setting, creating, or starting a relative path volume

### ISSUE THREAD

**Issue by benwalther** [docker/docker-py#599]
CLI docker throws this error:
```docker run -v ./test:test alpine```
```invalid value "./test:test" for flag -v: test is not an absolute path```

but docker-py does not:

    >>> c = docker.Client()
    >>> d = c.create_container(image="alpine",volumes="./testing:/example",command="/bin/sh")
    >>> print c,d 
    <docker.client.Client object at 0x7f7b5157f890> {u'Id': u'2c9a02c59eb7606885c10e1c87bac8666db6b9fcd9d8efa5e00ef80e92809384', u'Warnings': None}
    >>> c.start(d)
    >>>

**Comment by benwalther** [comment]
Note: the volume mount fails silently. I'd recommend a bug label; I should have mentioned that.

**Comment by shin-** [comment]
Sorry for the delay on this - You're not getting an error because you're not doing volume configuration properly.

```
In [1]: import docker

In [2]: c = docker.Client()

In [6]: cfg = docker.utils.create_host_config(binds={'./tests': { 'bind': '/vol1', 'ro': False }})

In [8]: container_id = c.create_container('busybox', 'ls /vol1', volumes=['/vol1'], host_config=cfg)
---------------------------------------------------------------------------
APIError: 500 Server Error: Internal Server Error ("cannot bind mount volume: ./tests volume paths must be absolute.")
```

We could add more validation arguably (for example to not let you set a string as the "volumes" param) but there's a limit to how much we can really do I think.(i.e., if you specify volumes but not binds, there's no way for docker-py to tell if that's an error, or simply the intent to have unbound volumes)
