### ISSUE TITLE
Hardening for URL request construction

### ISSUE THREAD

**Issue by fweimer** [docker/docker-py#697]
The `Client` class performs a lot URL construction like this:

        res = self._get(self._url("/exec/{0}/json".format(exec_id)))

This can be used to manipulate the query string if `exec_id` contains characters like `'?'` and `'/'`, which can lead to vulnerabilities elsewhere.  The client code should be fixed to reject such invalid parameters.

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1248031

**Comment by aanand** [comment]
Agreed. Perhaps we could write an `format`-like wrapper function which performs URL-escaping on its arguments before passing them to `format`.

**Comment by mrfuxi** [comment]
I would like to propose 3 options:

1. escape whole path in `_url`
 * Pro:
    - transparent to existing code
    - never to be forgotten
 * Con:
    - might need to be a bit less strict then if handling format argument (ie. `'/'`would be allowed because it would be in the path already)
2. wrapper suggested by @aanand 
 * Pro:
    - could be rather strict as most likely only images and container info will go there
 * Con:
    - has to be added every time, easy to forget/miss
    - current code would need to be modified
3. `_url` to accept `string` or `tuple` as first arg instead of just a `string`. Ie: `self._url(("/exec/{0}/json", exec_id), versioned_api=True)`. Then format would happen inside `_url`. Cleanup could be more strict on formatting args and less strict for complete path.
 * Pro:
    - harder to forget (passing a string would still be allowed)
    - could be rather strict as most likely only images and container info will go there
 * Con:
    - still possible to pass something dangerous
    - current code would need to be modified

I would still have a general question regarding: try to escape or just raise exception if something incorrect is found in path

**Comment by aanand** [comment]
Option 1 is no good from a security standpoint - if it allows `/`, then I can still mess with the path by putting `/` in an argument.

I don't really understand Option 3. If passing a string is still allowed, isn't it just as easy to forget?
