### ISSUE TITLE
Support for net aliases

### ISSUE THREAD

**Issue by dvenza** [docker/docker-py#982]
The API change to give network name aliases to containers was implemented here:
https://github.com/docker/docker/pull/19242

I cannot find this option exposed in create_container, should I look elsewhere?

**Comment by shin-** [comment]
Our networking documentation is seriously lacking, but the feature is there: https://github.com/docker/docker-py/blob/master/docker/api/network.py#L50

Example usage from our test suite: https://github.com/docker/docker-py/blob/master/tests/integration/network_test.py#L131-L143

**Comment by dvenza** [comment]
Thanks!
I use Swarm and use overlay networks, so I always pass a network name to the start_container call because I do not want to use the default docker network. How can I pass an alias there? From the command line I can pass aliases when I do `docker run`.
Should I call connect_to_network passing a network that is already connected, but adding the aliases I need?

**Comment by aanand** [comment]
@dvenza This should work (off the top of my head):

```python
client.create_container(
  image='busybox',
  command=['true'],
  net='mynetwork',
  networking_config=client.create_networking_config(
    endpoints_config={
      'mynetwork': client.create_endpoint_config(
        aliases=['foo', 'bar'],
      )
    }
  )
)
```

@shin- is right that the documentation is lacking - this is my fault, sorry!

**Comment by harpingon** [comment]
I've just tried that code for specifying alias, and I get:

endpoint_config.aliases param is not supported in API versions < 1.22

I'm running Docker 1.10.3 ...
$ docker --version
Docker version 1.10.3, build 20f81dd

But, with Swarm on tcp://localhost:4000

docker info

$ docker info
Containers: 14
 Running: 13
 Paused: 0
 Stopped: 1
Images: 25
Server Version: swarm/1.1.3

I do also get the same error without swarm though ...
$ docker -H tcp://localhost:2375 info
Containers: 8
 Running: 7
 Paused: 0
 Stopped: 1
Images: 102
Server Version: 1.10.3

So, what is the problem , because I have 1.10.3, I should be on API 1.22, yes?

Can see this with curl ...

curl http://localhost:2375/v1.22/info
{"ID":"XZQI:YF2Z:62DM:H7IF:JZJD:7SUE:VEC5:ON3M:2GJR:QMG4:SICL:I42Y","Containers":8,"ContainersRunning"

Docker responds to API v1.22 requests

I've probably missed something obvious, but, can't see what that might be so far

**Comment by shin-** [comment]
docker-py 1.7.x uses API version 1.21 by default. You can override that in the client constructor like this:
```python
import docker
c = docker.Client(version='1.22')
```

The upcoming 1.8.0 will use `1.22` by default.

**Comment by harpingon** [comment]
Thank you.
